import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
import Games, { Game } from '../api/Games';

export interface GameState {
    value: Game | undefined;
    status: 'idle' | 'loading' | 'failed';
  }

  const initialState: GameState = {
    value: undefined,
    status: 'idle',
  };

  export const changeAsync = createAsyncThunk(
    'game/fetchCount',
    async (amount: string) => {
      const response = Games["district53"];
      // The value we return becomes the `fulfilled` action payload
      return response;
    }
  );

  export const gameSlice = createSlice({
    name: 'game',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
      // Use the PayloadAction type to declare the contents of `action.payload`
      change: (state, action: PayloadAction<Game | undefined>) => {
        state.value = action.payload;
      },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    // extraReducers: (builder) => {
    //   builder
    //     .addCase(incrementAsync.pending, (state) => {
    //       state.status = 'loading';
    //     })
    //     .addCase(incrementAsync.fulfilled, (state, action) => {
    //       state.status = 'idle';
    //       state.value += action.payload;
    //     })
    //     .addCase(incrementAsync.rejected, (state) => {
    //       state.status = 'failed';
    //     });
    // },
  });
  
  export const {change } = gameSlice.actions;
  
  // The function below is called a selector and allows us to select a value from
  // the state. Selectors can also be defined inline where they're used instead of
  // in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
  export const selectGame = (state: RootState) => state.game.value;
  
  // We can also write thunks by hand, which may contain both sync and async logic.
  // Here's an example of conditionally dispatching actions based on current state.
//   export const incrementIfOdd =
//     (amount: number): AppThunk =>
//     (dispatch, getState) => {
//       const currentValue = selectCount(getState());
//       if (currentValue % 2 === 1) {
//         dispatch(change(amount));
//       }
//     };
  
  export default gameSlice.reducer;
  